name: Deploy to staging
on:
  push:
    branches:
      - main

jobs:
  redeploy-everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - name: Setup SSH and Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@137.184.33.129 << 'EOF'
            cd bms/ && git pull
            pnpm install
            pnpm run build
            pm2 restart fe-server
            pm2 restart ws-server
            pm2 restart http-server
          EOF
