name: Deploy to staging
on:
  push:
    branches:
      - main
jobs:
  redeploy-everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          echo "${{ secrets.kNOWN_HOSTS }}" > /home/runner/.ssh/known_hosts
          ssh -i ~/ssh_key root@137.184.33.129
          cd bms/ && git pull
          pnpm install
          pm2 run build
          pm2 restart fe-server
          pm2 restart ws-server
          pm2 restart http-server
   